env:
  browser: true
  node: true
  es6: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  # import plugin includes check for valid path in import statements
  - plugin:import/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - prettier
rules:
  no-console: 0
  linebreak-style:
    - error
    - unix
  prettier/prettier:
    - error
  react/prop-types: 0
  react/state-in-constructor: 0
  react/display-name: 0
  no-unused-vars: warn
settings:
  react:
    version: detect
  import/resolver:
    node:
      extensions: [".js", ".jsx"]
